/********************************************************************
* /Users/spada/Documents/XIPE/xperecon/src/PixiDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /Users/spada/Documents/XIPE/xperecon/src/PixiDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablePixiDict();
extern void G__cpp_setup_inheritancePixiDict();
extern void G__cpp_setup_typetablePixiDict();
extern void G__cpp_setup_memvarPixiDict();
extern void G__cpp_setup_globalPixiDict();
extern void G__cpp_setup_memfuncPixiDict();
extern void G__cpp_setup_funcPixiDict();
extern void G__set_cpp_environmentPixiDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/Users/spada/Documents/XIPE/xperecon/include/TMainGUI.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__PixiDictLN_TClass;
extern G__linked_taginfo G__PixiDictLN_TBuffer;
extern G__linked_taginfo G__PixiDictLN_TMemberInspector;
extern G__linked_taginfo G__PixiDictLN_TObject;
extern G__linked_taginfo G__PixiDictLN_TString;
extern G__linked_taginfo G__PixiDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR;
extern G__linked_taginfo G__PixiDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__PixiDictLN_basic_ifstreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__PixiDictLN_basic_ofstreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__PixiDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__PixiDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PixiDictLN_TObjArray;
extern G__linked_taginfo G__PixiDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__PixiDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PixiDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__PixiDictLN_TFile;
extern G__linked_taginfo G__PixiDictLN_TCanvas;
extern G__linked_taginfo G__PixiDictLN_TColor;
extern G__linked_taginfo G__PixiDictLN_TQObject;
extern G__linked_taginfo G__PixiDictLN_TTree;
extern G__linked_taginfo G__PixiDictLN_TBranch;
extern G__linked_taginfo G__PixiDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__PixiDictLN_TLine;
extern G__linked_taginfo G__PixiDictLN_TGObject;
extern G__linked_taginfo G__PixiDictLN_TGWindow;
extern G__linked_taginfo G__PixiDictLN_TGPicture;
extern G__linked_taginfo G__PixiDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__PixiDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__PixiDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PixiDictLN_TGFrame;
extern G__linked_taginfo G__PixiDictLN_TGCompositeFrame;
extern G__linked_taginfo G__PixiDictLN_TGLayoutHints;
extern G__linked_taginfo G__PixiDictLN_TGTextButton;
extern G__linked_taginfo G__PixiDictLN_TGVerticalFrame;
extern G__linked_taginfo G__PixiDictLN_TGHorizontalFrame;
extern G__linked_taginfo G__PixiDictLN_TGMainFrame;
extern G__linked_taginfo G__PixiDictLN_TGTransientFrame;
extern G__linked_taginfo G__PixiDictLN_TGGroupFrame;
extern G__linked_taginfo G__PixiDictLN_TGPopupMenu;
extern G__linked_taginfo G__PixiDictLN_TF1;
extern G__linked_taginfo G__PixiDictLN_TGButton;
extern G__linked_taginfo G__PixiDictLN_TGPictureButton;
extern G__linked_taginfo G__PixiDictLN_TGCheckButton;
extern G__linked_taginfo G__PixiDictLN_TGRadioButton;
extern G__linked_taginfo G__PixiDictLN_TGImageMap;
extern G__linked_taginfo G__PixiDictLN_TGLabel;
extern G__linked_taginfo G__PixiDictLN_TGTextBuffer;
extern G__linked_taginfo G__PixiDictLN_TGTextEntry;
extern G__linked_taginfo G__PixiDictLN_EMsgBoxIcon;
extern G__linked_taginfo G__PixiDictLN_TGMsgBox;
extern G__linked_taginfo G__PixiDictLN_TGMenuBar;
extern G__linked_taginfo G__PixiDictLN_TGHSlider;
extern G__linked_taginfo G__PixiDictLN_TGFileInfo;
extern G__linked_taginfo G__PixiDictLN_TH1F;
extern G__linked_taginfo G__PixiDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__PixiDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__PixiDictLN_TH1S;
extern G__linked_taginfo G__PixiDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__PixiDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__PixiDictLN_TH2F;
extern G__linked_taginfo G__PixiDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__PixiDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PixiDictLN_TStopwatch;
extern G__linked_taginfo G__PixiDictLN_TGaxis;
extern G__linked_taginfo G__PixiDictLN_TEllipse;
extern G__linked_taginfo G__PixiDictLN_PixelHit;
extern G__linked_taginfo G__PixiDictLN_THexagonCol;
extern G__linked_taginfo G__PixiDictLN_TEventDisplay;
extern G__linked_taginfo G__PixiDictLN_TInputFile;
extern G__linked_taginfo G__PixiDictLN_TDetector;
extern G__linked_taginfo G__PixiDictLN_Editor;
extern G__linked_taginfo G__PixiDictLN_TMainGUI;

/* STUB derived class for protected member access */
